# NumPy Exercises 
Now that we've learned about NumPy let's test your knowledge. 
We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros

In [4]:
zeroes_arr = np.zeros(10)
print(zeroes_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [5]:
ones_arr = np.ones(10)
print(ones_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [7]:
fives_arr = np.ones(10) * 5
print(fives_arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [10]:
arr_10_50 = np.arange(10, 51)
print(arr_10_50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [12]:
even_arr_10_50 = np.arange(10, 51, 2)
print(even_arr_10_50)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
arr_3d_0_8 = np.arange(0, 9).reshape(3, 3)
print(arr_3d_0_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [27]:
identity_matrix_3 = np.identity(3)
identity_matrix_3_3 = np.eye(3)
print(identity_matrix_3)
print(identity_matrix_3_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [19]:
random_n_0_1 = np.random.rand()
print(random_n_0_1)

0.7302823889161214


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [23]:
arr_standard_normal_distribution_25 = np.random.normal(0, 1, 25)
print(arr_standard_normal_distribution_25)

[ 0.54755451 -0.11198247  0.19850072  1.44158962 -0.29000471 -1.11240372
 -0.1771538   0.98292062 -0.58782847 -0.42439523  0.7870989   0.7621252
 -0.53360052 -0.12443764  2.4780954   0.50161116 -0.54273026 -0.52238032
 -0.3726163   0.97582038  0.83280495 -1.0764389  -1.28917064  0.4566065
 -0.99349253]


#### Create the following matrix:

In [26]:
arr_001_1 = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(arr_001_1)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [31]:
linearly_spaced_arr_20 = np.linspace(0, 1, 20)
print(linearly_spaced_arr_20)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [33]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
arr_from_12_25 = mat[2:, 1:]
print(arr_from_12_25)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [35]:
item_20 = mat[3][4]
print(item_20)

20


20

In [38]:
items_2_7_12 = mat[:3, 1:2]
print(items_2_7_12)

[[ 2]
 [ 7]
 [12]]


array([[ 2],
       [ 7],
       [12]])

In [39]:
last_row = mat[-1]
print(last_row)

[21 22 23 24 25]


array([21, 22, 23, 24, 25])

In [48]:
last_2_rows = mat[-2:, :]
print(last_2_rows)

[[16 17 18 19 20]
 [21 22 23 24 25]]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [50]:
mat_sum = mat.sum()
print(mat_sum)

325


325

#### Get the standard deviation of the values in mat

In [52]:
mat_std = mat.std
print(mat_std())

7.211102550927978


7.2111025509279782

#### Get the sum of all the columns in mat

In [54]:
column_sum = mat.sum(axis=0)
print(column_sum)

[55 60 65 70 75]


array([55, 60, 65, 70, 75])

# Great Job!